<?php

namespace Database\Seeders;
use App\Models\City;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::create(['name' => 'MEDELLIN','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ABEJORRAL','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ABRIAQUI','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ALEJANDRIA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'AMAGA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'AMALFI','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ANDES','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ANGELOPOLIS','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ANGOSTURA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ANORI','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ANTIOQUIA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ANZA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'APARTADO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ARBOLETES','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ARGELIA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ARMENIA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'BARBOSA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'BELMIRA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'BELLO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'BETANIA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'BETULIA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'BOLIVAR','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'BRICEÑO','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'BURITICA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'CACERES','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'CAICEDO','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'CALDAS' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'CAMPAMENTO','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'CAÑASGORDAS' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'CARACOLI' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'CARAMANTA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'CAREPA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'CARMEN DE VIBORAL' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'CAROLINA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'CAUCASIA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'CHIGORODO','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'CISNEROS' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'COCORNA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'CONCEPCION','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'CONCORDIA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'COPACABANA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'DABEIBA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'DON MATIAS','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'EBEJICO','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'EL BAGRE' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ENTRERRIOS','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ENVIGADO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'FREDONIA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'FRONTINO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'GIRALDO','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'GIRARDOTA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'GOMEZ PLATA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'GRANADA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'GUADALUPE','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'GUARNE' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'GUATAPE','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'HELICONIA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'HISPANIA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ITAGUI' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ITUANGO','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'JARDIN' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'JERICO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'LA CEJA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'LA ESTRELLA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'LA PINTADA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'LA UNION' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'LIBORINA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'MACEO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'MARINILLA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'MONTEBELLO','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'MURINDO','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'MUTATA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'NARIÑO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'NECOCLI','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'NECHI' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'OLAYA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'PEÑOL' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'PEQUE' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'PUEBLORRICO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO BERRIO','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO NARE (LA MAGDALENA)' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO TRIUNFO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'REMEDIOS' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'RETIRO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'RIONEGRO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SABANALARGA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SABANETA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SALGAR' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN ANDRES','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN CARLOS','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN FRANCISCO','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JERONIMO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JOSE DE LA MONTAÑA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JUAN DE URABA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN LUIS' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN PEDRO','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN PEDRO DE URABA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN RAFAEL','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN ROQUE','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN VICENTE' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA BARBARA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA ROSA DE OSOS' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTO DOMINGO','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTUARIO','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SEGOVIA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SONSON' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'SOPETRAN' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'TAMESIS','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'TARAZA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'TARSO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'TITIRIBI' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'TOLEDO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'TURBO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'URAMITA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'URRAO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'VALDIVIA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'VALPARAISO','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'VEGACHI','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'VENECIA','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'VIGIA DEL FUERTE','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'YALI','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'YARUMAL','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'YOLOMBO','department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'YONDO' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'ZARAGOZA' ,'department_id' => 1 ,  'cost' =>10.000]);
        City::create(['name' => 'BARRANQUILLA' ,'department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'BARANOA','department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'CAMPO DE LA CRUZ','department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'CANDELARIA','department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'GALAPA' ,'department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'JUAN DE ACOSTA' ,'department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'LURUACO','department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'MALAMBO','department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'MANATI' ,'department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'PALMAR DE VARELA','department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'PIOJO' ,'department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'POLO NUEVO','department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'PONEDERA' ,'department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO COLOMBIA','department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'REPELON','department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'SABANAGRANDE' ,'department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'SABANALARGA' ,'department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA LUCIA' ,'department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTO TOMAS' ,'department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'SOLEDAD','department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'SUAN','department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'TUBARA' ,'department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'USIACURI' ,'department_id' => 2 ,  'cost' =>10.000]);
        City::create(['name' => 'Santa Fe de Bogotá' ,'department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'USAQUEN','department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'CHAPINERO','department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA FE' ,'department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN CRISTOBAL','department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'USME','department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'TUNJUELITO','department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'BOSA','department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'KENNEDY','department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'FONTIBON' ,'department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'ENGATIVA' ,'department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'SUBA','department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'BARRIOS UNIDOS' ,'department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'TEUSAQUILLO' ,'department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'MARTIRES' ,'department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'ANTONIO NARIÑO' ,'department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'PUENTE ARANDA','department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'CANDELARIA','department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'RAFAEL URIBE' ,'department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'CIUDAD BOLIVAR' ,'department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'SUMAPAZ','department_id' => 3 ,  'cost' =>10.000]);
        City::create(['name' => 'CARTAGENA' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'ACHI','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'ALTOS DEL ROSARIO' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'ARENAL' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'ARJONA' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'ARROYOHONDO' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'BARRANCO DE LOBA','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'CALAMAR','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'CANTAGALLO','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'CICUCO' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'CORDOBA','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'CLEMENCIA','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'EL CARMEN DE BOLIVAR' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'EL GUAMO' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'EL PEÑON' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'HATILLO DE LOBA','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'MAGANGUE' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'MAHATES','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'MARGARITA','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'MARIA LA BAJA','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'MONTECRISTO' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'MOMPOS' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'MORALES','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'PINILLOS' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'REGIDOR','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'RIO VIEJO','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN CRISTOBAL','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN ESTANISLAO' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN FERNANDO' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JACINTO' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JACINTO DEL CAUCA','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JUAN NEPOMUCENO','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN MARTIN DE LOBA' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN PABLO','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA CATALINA' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA ROSA','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA ROSA DEL SUR' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'SIMITI' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'SOPLAVIENTO' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'TALAIGUA NUEVO' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'TIQUISIO [PUERTO RICO','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'TURBACO','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'TURBANA','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLANUEVA','department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'ZAMBRANO' ,'department_id' => 4 ,  'cost' =>10.000]);
        City::create(['name' => 'TUNJA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'ALMEIDA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'AQUITANIA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'ARCABUCO' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'BELEN' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'BERBEO' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'BETEITIVA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'BOAVITA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'BOYACA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'BRICEÑO','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'BUENAVISTA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'BUSBANZA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'CALDAS' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'CAMPOHERMOSO' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'CERINZA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'CHINAVITA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'CHIQUINQUIRA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'CHISCAS','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'CHITA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'CHITARAQUE','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'CHIVATA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'CIENEGA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'COMBITA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'COPER' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'CORRALES' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'COVARACHIA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'CUBARA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'CUCAITA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'CUITIVA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'CHIQUIZA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'CHIVOR' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'DUITAMA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'EL COCUY' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'EL ESPINO','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'FIRAVITOBA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'FLORESTA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'GACHANTIVA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'GAMEZA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'GARAGOA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'GUACAMAYAS','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'GUATEQUE' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'GUAYATA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'GUICAN' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'IZA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'JENESANO' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'JERICO' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'LABRANZAGRANDE' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'LA CAPILLA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'LA VICTORIA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'LA UVITA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLA DE LEIVA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'MACANAL','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'MARIPI' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'MIRAFLORES','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'MONGUA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'MONGUI' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'MONIQUIRA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'MOTAVITA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'MUZO','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'NOBSA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'NUEVO COLON' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'OICATA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'OTANCHE','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'PACHAVITA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'PAEZ','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'PAIPA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'PAJARITO' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'PANQUEBA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'PAUNA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'PAYA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'PAZ DEL RIO' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'PESCA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'PISBA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO BOYACA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'QUIPAMA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'RAMIRIQUI','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'RAQUIRA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'RONDON' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SABOYA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SACHICA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SAMACA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN EDUARDO' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JOSE DE PARE','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN LUIS DE GACENO' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN MATEO','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN MIGUEL DE SEMA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN PABLO DE BORBUR','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTANA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA MARIA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA ROSA DE VITERBO','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA SOFIA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SATIVANORTE' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SATIVASUR','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SIACHOQUE','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SOATA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SOCOTA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SOCHA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SOGAMOSO' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SOMONDOCO','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SORA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SOTAQUIRA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SORACA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SUSACON','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SUTAMARCHAN' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'SUTATENZA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'TASCO' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'TENZA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'TIBANA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'TIBASOSA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'TINJACA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'TIPACOQUE','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'TOCA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'TOGUI' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'TOPAGA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'TOTA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'TUNUNGUA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'TURMEQUE' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'TUTA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'TUTASA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'UMBITA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'VENTAQUEMADA' ,'department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'VIRACACHA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'ZETAQUIRA','department_id' => 5 ,  'cost' =>10.000]);
        City::create(['name' => 'MANIZALES','department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'AGUADAS','department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'ANSERMA','department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'ARANZAZU' ,'department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'BELALCAZAR','department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'CHINCHINA','department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'FILADELFIA','department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'LA DORADA','department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'LA MERCED','department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'MANZANARES','department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'MARMATO','department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'MARQUETALIA' ,'department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'MARULANDA','department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'NEIRA' ,'department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'NORCASIA' ,'department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'PACORA' ,'department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'PALESTINA','department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'PENSILVANIA' ,'department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'RIOSUCIO' ,'department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'RISARALDA','department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'SALAMINA' ,'department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'SAMANA' ,'department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JOSE' ,'department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'SUPIA' ,'department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'VICTORIA' ,'department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLAMARIA','department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'VITERBO','department_id' => 6 ,  'cost' =>10.000]);
        City::create(['name' => 'FLORENCIA','department_id' => 7 ,  'cost' =>10.000]);
        City::create(['name' => 'ALBANIA','department_id' => 7 ,  'cost' =>10.000]);
        City::create(['name' => 'BELEN DE LOS ANDAQUIES','department_id' => 7 ,  'cost' =>10.000]);
        City::create(['name' => 'CARTAGENA DEL CHAIRA' ,'department_id' => 7 ,  'cost' =>10.000]);
        City::create(['name' => 'CURILLO','department_id' => 7 ,  'cost' =>10.000]);
        City::create(['name' => 'EL DONCELLO' ,'department_id' => 7 ,  'cost' =>10.000]);
        City::create(['name' => 'EL PAUJIL','department_id' => 7 ,  'cost' =>10.000]);
        City::create(['name' => 'LA MONTAÑITA' ,'department_id' => 7 ,  'cost' =>10.000]);
        City::create(['name' => 'MILAN' ,'department_id' => 7 ,  'cost' =>10.000]);
        City::create(['name' => 'MORELIA','department_id' => 7 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO RICO' ,'department_id' => 7 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JOSE DE FRAGUA' ,'department_id' => 7 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN VICENTE DEL CAGUAN','department_id' => 7 ,  'cost' =>10.000]);
        City::create(['name' => 'SOLANO' ,'department_id' => 7 ,  'cost' =>10.000]);
        City::create(['name' => 'SOLITA' ,'department_id' => 7 ,  'cost' =>10.000]);
        City::create(['name' => 'VALPARAISO','department_id' => 7 ,  'cost' =>10.000]);
        City::create(['name' => 'POPAYAN','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'ALMAGUER' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'ARGELIA','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'BALBOA' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'BOLIVAR','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'BUENOS AIRES' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'CAJIBIO','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'CALDONO','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'CALOTO' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'CORINTO','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'EL TAMBO' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'FLORENCIA','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'GUAPI' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'INZA','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'JAMBALO','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'LA SIERRA','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'LA VEGA','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'LOPEZ [MICAY' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'MERCADERES','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'MIRANDA','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'MORALES','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'PADILLA','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'PAEZ (BELALCAZAR)' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'PATIA (EL BORDO)','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'PIAMONTE' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'PIENDAMO' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO TEJADA','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'PURACE (COCONUCO)' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'ROSAS' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN SEBASTIAN','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTANDER DE QUILICHAO','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA ROSA','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'SILVIA' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'SOTARA (PAISPAMBA)' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'SUAREZ' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'TIMBIO' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'TIMBIQUI' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'TORIBIO','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'TOTORO' ,'department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLARICA','department_id' => 8 ,  'cost' =>10.000]);
        City::create(['name' => 'VALLEDUPAR','department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'AGUACHICA','department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'AGUSTIN CODAZZI','department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'ASTREA' ,'department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'BECERRIL' ,'department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'BOSCONIA' ,'department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'CHIMICHAGUA' ,'department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'CHIRIGUANA','department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'CURUMANI' ,'department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'EL COPEY' ,'department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'EL PASO','department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'GAMARRA','department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'GONZALEZ' ,'department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'LA GLORIA','department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'LA JAGUA IBIRICO','department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'MANAURE' ,'department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'PAILITAS' ,'department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'PELAYA' ,'department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'PUEBLO BELLO' ,'department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'RIO DE ORO','department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'LA PAZ (ROBLES)','department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN ALBERTO' ,'department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN DIEGO','department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN MARTIN','department_id' => 9 ,  'cost' =>10.000]);
        City::create(['name' => 'TAMALAMEQUE' ,'department_id' => 9 ,  'cost' =>10.000]);
        
        City::create(['name' => 'MONTERIA' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'AYAPEL' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'BUENAVISTA','department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'CANALETE' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'CERETE' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'CHIMA' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'CHINU' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'CIENAGA DE ORO' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'COTORRA','department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'LA APARTADA' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'LORICA' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'LOS CORDOBAS' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'MOMIL' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'MONTELIBANO' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'MOÑITOS','department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'PLANETA RICA' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'PUEBLO NUEVO' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO ESCONDIDO','department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO LIBERTADOR' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'PURISIMA' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'SAHAGUN','department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN ANDRES SOTAVENTO' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN ANTERO','department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN BERNARDO DEL VIENTO' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN CARLOS','department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN PELAYO','department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'TIERRALTA','department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'VALENCIA' ,'department_id' => 10 ,  'cost' =>10.000]);
        City::create(['name' => 'AGUA DE DIOS' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'ALBAN' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'ANAPOIMA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'ANOLAIMA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'ARBELAEZ' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'BELTRAN','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'BITUIMA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'BOJACA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'CABRERA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'CACHIPAY' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'CAJICA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'CAPARRAPI','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'CAQUEZA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'CARMEN DE CARUPA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'CHAGUANI' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'CHIA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'CHIPAQUE' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'CHOACHI','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'CHOCONTA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'COGUA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'COTA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'CUCUNUBA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'EL COLEGIO','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'EL PEÑON' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'EL ROSAL' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'FACATATIVA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'FOMEQUE','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'FOSCA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'FUNZA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'FUQUENE','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'FUSAGASUGA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'GACHALA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'GACHANCIPA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'GACHETA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'GAMA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'GIRARDOT' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'GRANADA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'GUACHETA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'GUADUAS','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'GUASCA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'GUATAQUI' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'GUATAVITA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'GUAYABAL DE SIQUIMA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'GUAYABETAL','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'GUTIERREZ','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'JERUSALEN','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'JUNIN' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'LA CALERA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'LA MESA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'LA PALMA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'LA PEÑA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'LA VEGA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'LENGUAZAQUE' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'MACHETA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'MADRID' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'MANTA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'MEDINA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'MOSQUERA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'NARIÑO' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'NEMOCON','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'NILO','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'NIMAIMA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'NOCAIMA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'VENECIA ','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'PACHO' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'PAIME' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'PANDI' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'PARATEBUENO' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'PASCA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO SALGAR','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'PULI','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'QUEBRADANEGRA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'QUETAME','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'QUIPILE','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'APULO' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'RICAURTE' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN ANTONIO DEL TEQUENDAMA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN BERNARDO' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN CAYETANO' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN FRANCISCO','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JUAN DE RIOSECO','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SASAIMA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SESQUILE' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SIBATE' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SILVANIA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SIMIJACA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SOACHA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SOPO','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SUBACHOQUE','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SUESCA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SUPATA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SUSA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'SUTATAUSA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'TABIO' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'TAUSA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'TENA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'TENJO' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'TIBACUY','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'TIBIRITA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'TOCAIMA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'TOCANCIPA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'TOPAIPI','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'UBALA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'UBAQUE' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'UBATE' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'UNE','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'UTICA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'VERGARA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'VIANI' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLAGOMEZ','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLAPINZON' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLETA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'VIOTA' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'YACOPI' ,'department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'ZIPACON','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'ZIPAQUIRA','department_id' => 11 ,  'cost' =>10.000]);
        City::create(['name' => 'QUIBDO' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'ACANDI' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'ALTO BAUDO' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'ATRATO' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'BAGADO' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'BAHIA SOLANO [MUTIS','department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'BAJO BAUDO ' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'BOJAYA ','department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'CANTON DE SAN PABLO' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'CONDOTO','department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'EL CARMEN DE ATRATO','department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'LITORAL DEL BAJO SAN JUAN' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'ISTMINA','department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'JURADO' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'LLORO' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'MEDIO ATRATO' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'MEDIO BAUDO' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'NOVITA' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'NUQUI' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'RIOQUITO' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'RIOSUCIO' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JOSE DEL PALMAR','department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'SIPI','department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'TADO','department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'UNGUIA' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'UNION PANAMERICANA' ,'department_id' => 12 ,  'cost' =>10.000]);
        City::create(['name' => 'NEIVA' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'ACEVEDO','department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'AGRADO' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'AIPE','department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'ALGECIRAS','department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'ALTAMIRA' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'BARAYA' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'CAMPOALEGRE' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'COLOMBIA' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'ELIAS' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'GARZON' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'GIGANTE','department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'GUADALUPE','department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'HOBO','department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'IQUIRA' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'ISNOS','department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'LA ARGENTINA' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'LA PLATA' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'NATAGA' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'OPORAPA','department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'PAICOL' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'PALERMO','department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'PALESTINA','department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'PITAL' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'PITALITO' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'RIVERA' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'SALADOBLANCO' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN AGUSTIN' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA MARIA' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'SUAZA' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'TARQUI' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'TESALIA','department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'TELLO' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'TERUEL' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'TIMANA' ,'department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLAVIEJA','department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'YAGUARA','department_id' => 13 ,  'cost' =>10.000]);
        City::create(['name' => 'RIOHACHA' ,'department_id' => 14 ,  'cost' =>10.000]);
        City::create(['name' => 'BARRANCAS','department_id' => 14 ,  'cost' =>10.000]);
        City::create(['name' => 'DIBULLA','department_id' => 14 ,  'cost' =>10.000]);
        City::create(['name' => 'DISTRACCION' ,'department_id' => 14 ,  'cost' =>10.000]);
        City::create(['name' => 'EL MOLINO','department_id' => 14 ,  'cost' =>10.000]);
        City::create(['name' => 'FONSECA','department_id' => 14 ,  'cost' =>10.000]);
        City::create(['name' => 'HATONUEVO','department_id' => 14 ,  'cost' =>10.000]);
        City::create(['name' => 'LA JAGUA DEL PILAR' ,'department_id' => 14 ,  'cost' =>10.000]);
        City::create(['name' => 'MAICAO' ,'department_id' => 14 ,  'cost' =>10.000]);
        City::create(['name' => 'MANAURE','department_id' => 14 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JUAN DEL CESAR' ,'department_id' => 14 ,  'cost' =>10.000]);
        City::create(['name' => 'URIBIA' ,'department_id' => 14 ,  'cost' =>10.000]);
        City::create(['name' => 'URUMITA','department_id' => 14 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLANUEVA','department_id' => 14 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA MARTA' ,'department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'ALGARROBO','department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'ARACATACA','department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'ARIGUANI' ,'department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'CERRO SAN ANTONIO' ,'department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'CHIVOLO','department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'CIENAGA','department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'CONCORDIA','department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'EL BANCO' ,'department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'EL PIÑON' ,'department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'EL RETEN' ,'department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'FUNDACION','department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'GUAMAL' ,'department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'PEDRAZA','department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'PIJIÑO DEL CARMEN ' ,'department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'PIVIJAY','department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'PLATO' ,'department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'PUEBLOVIEJO' ,'department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'REMOLINO' ,'department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'SABANAS DE SAN ANGEL' ,'department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'SALAMINA' ,'department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN SEBASTIAN DE BUENAVISTA','department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN ZENON','department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA ANA','department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'SITIONUEVO','department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'TENERIFE' ,'department_id' => 15 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLAVICENCIO','department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'ACACIAS','department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'BARRANCA DE UPIA','department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'CABUYARO' ,'department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'CASTILLA LA NUEVA' ,'department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN LUIS DE CUBARRAL' ,'department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'CUMARAL','department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'EL CALVARIO' ,'department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'EL CASTILLO' ,'department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'EL DORADO','department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'FUENTE DE ORO','department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'GRANADA','department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'GUAMAL' ,'department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'MAPIRIPAN','department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'MESETAS','department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'LA MACARENA' ,'department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'LA URIBE' ,'department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'LEJANIAS' ,'department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO CONCORDIA','department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO GAITAN','department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO LOPEZ' ,'department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO LLERAS','department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO RICO' ,'department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'RESTREPO' ,'department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN CARLOS DE GUAROA' ,'department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JUAN DE ARAMA' ,'department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JUANITO' ,'department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN MARTIN','department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'VISTAHERMOSA' ,'department_id' => 16 ,  'cost' =>10.000]);
        City::create(['name' => 'PASTO SAN JUAN DE PASTO' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'ALBAN SAN JOSE','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'ALDANA' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'ANCUYA' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'ARBOLEDA ' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'BARBACOAS','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'BELEN' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'BUESACO','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'COLON (GENOVA)' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'CONSACA','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'CONTADERO','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'CORDOBA','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'CUASPUD (CARLOSAMA)','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'CUMBAL' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'CUMBITARA','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'CHACHAGUI','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'EL CHARCO','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'EL PEÑOL' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'EL ROSARIO','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'EL TABLON','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'EL TAMBO' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'FUNES' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'GUACHUCAL','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'GUAITARILLA' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'GUALMATAN','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'ILES','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'IMUES' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'IPIALES','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'LA CRUZ','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'LA FLORIDA','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'LA LLANADA','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'LA TOLA','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'LA UNION' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'LEIVA' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'LINARES','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'LOS ANDES','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'MAGUI (PAYAN)','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'MALLAMA' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'MOSQUERA' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'OLAYA HERRERA' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'OSPINA' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'FRANCISCO PIZARRO ' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'POLICARPA','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'POTOSI' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'PROVIDENCIA' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERRES','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'PUPIALES' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'RICAURTE' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'ROBERTO PAYAN' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'SAMANIEGO','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'SANDONA','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN BERNARDO' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN LORENZO' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN PABLO','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN PEDRO DE CARTAGO' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA BARBARA )' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA CRUZ ','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'SAPUYES','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'TAMINANGO','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'TANGUA' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'TUMACO' ,'department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'TUQUERRES','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'YACUANQUER','department_id' => 17 ,  'cost' =>10.000]);
        City::create(['name' => 'CUCUTA' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'ABREGO' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'ARBOLEDAS','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'BOCHALEMA','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'BUCARASICA','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'CACOTA' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'CACHIRA','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'CHINACOTA','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'CHITAGA','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'CONVENCION','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'CUCUTILLA','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'DURANIA','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'EL CARMEN','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'EL TARRA' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'EL ZULIA' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'GRAMALOTE','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'HACARI' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'HERRAN' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'LABATECA' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'LA ESPERANZA' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'LA PLAYA' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'LOS PATIOS','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'LOURDES','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'MUTISCUA' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'OCAÑA' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'PAMPLONA' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'PAMPLONITA','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO SANTANDER','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'RAGONVALIA','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'SALAZAR','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN CALIXTO' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN CAYETANO' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTIAGO' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'SARDINATA','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'SILOS' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'TEORAMA','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'TIBU','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'TOLEDO' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLACARO','department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLA DEL ROSARIO' ,'department_id' => 18 ,  'cost' =>10.000]);
        City::create(['name' => 'ARMENIA','department_id' => 19 ,  'cost' =>10.000]);
        City::create(['name' => 'BUENAVISTA','department_id' => 19 ,  'cost' =>10.000]);
        City::create(['name' => 'CALARCA','department_id' => 19 ,  'cost' =>10.000]);
        City::create(['name' => 'CIRCASIA' ,'department_id' => 19 ,  'cost' =>10.000]);
        City::create(['name' => 'CORDOBA','department_id' => 19 ,  'cost' =>10.000]);
        City::create(['name' => 'FILANDIA' ,'department_id' => 19 ,  'cost' =>10.000]);
        City::create(['name' => 'GENOVA' ,'department_id' => 19 ,  'cost' =>10.000]);
        City::create(['name' => 'LA TEBAIDA','department_id' => 19 ,  'cost' =>10.000]);
        City::create(['name' => 'MONTENEGRO','department_id' => 19 ,  'cost' =>10.000]);
        City::create(['name' => 'PIJAO' ,'department_id' => 19 ,  'cost' =>10.000]);
        City::create(['name' => 'QUIMBAYA' ,'department_id' => 19 ,  'cost' =>10.000]);
        City::create(['name' => 'SALENTO','department_id' => 19 ,  'cost' =>10.000]);
        City::create(['name' => 'PEREIRA','department_id' => 20 ,  'cost' =>10.000]);
        City::create(['name' => 'APIA','department_id' => 20 ,  'cost' =>10.000]);
        City::create(['name' => 'BALBOA' ,'department_id' => 20 ,  'cost' =>10.000]);
        City::create(['name' => 'BELEN DE UMBRIA','department_id' => 20 ,  'cost' =>10.000]);
        City::create(['name' => 'DOS QUEBRADAS','department_id' => 20 ,  'cost' =>10.000]);
        City::create(['name' => 'GUATICA','department_id' => 20 ,  'cost' =>10.000]);
        City::create(['name' => 'LA CELIA' ,'department_id' => 20 ,  'cost' =>10.000]);
        City::create(['name' => 'LA VIRGINIA' ,'department_id' => 20 ,  'cost' =>10.000]);
        City::create(['name' => 'MARSELLA' ,'department_id' => 20 ,  'cost' =>10.000]);
        City::create(['name' => 'MISTRATO' ,'department_id' => 20 ,  'cost' =>10.000]);
        City::create(['name' => 'PUEBLO RICO' ,'department_id' => 20 ,  'cost' =>10.000]);
        City::create(['name' => 'QUINCHIA' ,'department_id' => 20 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA ROSA DE CABAL','department_id' => 20 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTUARIO','department_id' => 20 ,  'cost' =>10.000]);
        City::create(['name' => 'BUCARAMANGA' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'AGUADA' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'ALBANIA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'ARATOCA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'BARBOSA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'BARICHARA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'BARRANCABERMEJA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'BETULIA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'BOLIVAR','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'CABRERA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'CALIFORNIA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'CAPITANEJO','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'CARCASI','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'CEPITA' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'CERRITO','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'CHARALA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'CHARTA' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'CHIMA' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'CHIPATA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'CIMITARRA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'CONCEPCION','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'CONFINES' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'CONTRATACION' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'COROMORO' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'CURITI' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'EL CARMEN DE CHUCURY' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'EL GUACAMAYO' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'EL PEÑON' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'EL PLAYON','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'ENCINO' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'ENCISO' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'FLORIAN','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'FLORIDABLANCA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'GALAN' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'GAMBITA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'GIRON' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'GUACA' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'GUADALUPE','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'GUAPOTA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'GUAVATA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'GUEPSA' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'HATO','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'JESUS MARIA' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'JORDAN' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'LA BELLEZA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'LANDAZURI','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'LA PAZ' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'LEBRIJA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'LOS SANTOS','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'MACARAVITA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'MALAGA' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'MATANZA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'MOGOTES','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'MOLAGAVITA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'OCAMONTE' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'OIBA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'ONZAGA' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'PALMAR' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'PALMAS DEL SOCORRO' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'PARAMO' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'PIEDECUESTA' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'PINCHOTE' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'PUENTE NACIONAL','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO PARRA' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO WILCHES' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'RIONEGRO' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'SABANA DE TORRES','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN ANDRES','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN BENITO','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN GIL','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JOAQUIN' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JOSE DE MIRANDA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN MIGUEL','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN VICENTE DE CHUCURI','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA BARBARA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA HELENA DEL OPON','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'SIMACOTA' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'SOCORRO','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'SUAITA' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'SUCRE' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'SURATA' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'TONA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'VALLE SAN JOSE' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'VELEZ' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'VETAS' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLANUEVA','department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'ZAPATOCA' ,'department_id' => 21 ,  'cost' =>10.000]);
        City::create(['name' => 'SINCELEJO','department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'BUENAVISTA','department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'CAIMITO','department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'COLOSO (RICAURTE)' ,'department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'COROZAL','department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'CHALAN' ,'department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'GALERAS (NUEVA GRANADA)' ,'department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'GUARANDA' ,'department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'LA UNION' ,'department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'LOS PALMITOS' ,'department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'MAJAGUAL' ,'department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'MORROA' ,'department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'OVEJAS' ,'department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'PALMITO','department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'SAMPUES','department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN BENITO ABAD','department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JUAN DE BETULIA','department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN MARCOS','department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN ONOFRE','department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN PEDRO','department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'SINCE' ,'department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'SUCRE' ,'department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'TOLU','department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'TOLUVIEJO','department_id' => 22 ,  'cost' =>10.000]);
        City::create(['name' => 'IBAGUE' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'ALPUJARRA','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'ALVARADO' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'AMBALEMA' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'ANZOATEGUI','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'ARMERO (GUAYABAL)' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'ATACO' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'CAJAMARCA','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'CARMEN APICALA' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'CASABIANCA','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'CHAPARRAL','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'COELLO' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'COYAIMA','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'CUNDAY' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'DOLORES','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'ESPINAL','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'FALAN' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'FLANDES','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'FRESNO' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'GUAMO' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'HERVEO' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'HONDA' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'ICONONZO' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'LERIDA' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'LIBANO' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'MARIQUITA','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'MELGAR' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'MURILLO','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'NATAGAIMA','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'ORTEGA' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'PALOCABILDO' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'PIEDRAS','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'PLANADAS' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'PRADO' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'PURIFICACION' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'RIOBLANCO','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'RONCESVALLES' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'ROVIRA' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'SALDAÑA','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN ANTONIO' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN LUIS' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA ISABEL' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'SUAREZ' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'VALLE DE SAN JUAN' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'VENADILLO','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLAHERMOSA' ,'department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLARRICA','department_id' => 23 ,  'cost' =>10.000]);
        City::create(['name' => 'CALI (SANTIAGO DE CALI)' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'ALCALA' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'ANDALUCIA','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'ANSERMANUEVO' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'ARGELIA','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'BOLIVAR','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'BUENAVENTURA' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'BUGA','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'BUGALAGRANDE' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'CAICEDONIA','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'CALIMA (DARIEN)','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'CANDELARIA','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'CARTAGO','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'DAGUA' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'EL AGUILA','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'EL CAIRO' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'EL CERRITO','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'EL DOVIO' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'FLORIDA','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'GINEBRA','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'GUACARI','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'JAMUNDI','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'LA CUMBRE','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'LA UNION' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'LA VICTORIA' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'OBANDO' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'PALMIRA','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'PRADERA','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'RESTREPO' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'RIOFRIO','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'ROLDANILLO','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN PEDRO','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'SEVILLA','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'TORO','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'TRUJILLO' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'TULUA' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'ULLOA' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'VERSALLES','department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'VIJES' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'YOTOCO' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'YUMBO' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'ZARZAL' ,'department_id' => 24 ,  'cost' =>10.000]);
        City::create(['name' => 'ARAUCA' ,'department_id' => 25 ,  'cost' =>10.000]);
        City::create(['name' => 'ARAUQUITA','department_id' => 25 ,  'cost' =>10.000]);
        City::create(['name' => 'CRAVO NORTE' ,'department_id' => 25 ,  'cost' =>10.000]);
        City::create(['name' => 'FORTUL' ,'department_id' => 25 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO RONDON','department_id' => 25 ,  'cost' =>10.000]);
        City::create(['name' => 'SARAVENA' ,'department_id' => 25 ,  'cost' =>10.000]);
        City::create(['name' => 'TAME','department_id' => 25 ,  'cost' =>10.000]);
        City::create(['name' => 'YOPAL' ,'department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'AGUAZUL','department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'CHAMEZA','department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'HATO COROZAL' ,'department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'LA SALINA','department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'MANI','department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'MONTERREY','department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'NUNCHIA','department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'OROCUE' ,'department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'PAZ DE ARIPORO' ,'department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'PORE','department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'RECETOR','department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'SABANALARGA' ,'department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'SACAMA' ,'department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN LUIS DE PALENQUE' ,'department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'TAMARA' ,'department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'TAURAMENA','department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'TRINIDAD' ,'department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLANUEVA','department_id' => 26 ,  'cost' =>10.000]);
        City::create(['name' => 'MOCOA' ,'department_id' => 27 ,  'cost' =>10.000]);
        City::create(['name' => 'COLON' ,'department_id' => 27 ,  'cost' =>10.000]);
        City::create(['name' => 'ORITO' ,'department_id' => 27 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO ASIS' ,'department_id' => 27 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO CAICEDO' ,'department_id' => 27 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO GUZMAN','department_id' => 27 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO LEGUIZAMO','department_id' => 27 ,  'cost' =>10.000]);
        City::create(['name' => 'SIBUNDOY' ,'department_id' => 27 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN FRANCISCO','department_id' => 27 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN MIGUEL','department_id' => 27 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTIAGO' ,'department_id' => 27 ,  'cost' =>10.000]);
        City::create(['name' => 'LA HORMIGA' ,'department_id' => 27 ,  'cost' =>10.000]);
        City::create(['name' => 'VILLAGARZON' ,'department_id' => 27 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN ANDRES','department_id' => 28 ,  'cost' =>10.000]);
        City::create(['name' => 'PROVIDENCIA' ,'department_id' => 28 ,  'cost' =>10.000]);
        City::create(['name' => 'LETICIA','department_id' => 29 ,  'cost' =>10.000]);
        City::create(['name' => 'EL ENCANTO','department_id' => 29 ,  'cost' =>10.000]);
        City::create(['name' => 'LA CHORRERA' ,'department_id' => 29 ,  'cost' =>10.000]);
        City::create(['name' => 'LA PEDRERA','department_id' => 29 ,  'cost' =>10.000]);
        City::create(['name' => 'LA VICTORIA' ,'department_id' => 29 ,  'cost' =>10.000]);
        City::create(['name' => 'MIRITI-PARANA','department_id' => 29 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO ALEGRIA' ,'department_id' => 29 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO ARICA' ,'department_id' => 29 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO NARIÑO','department_id' => 29 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO SANTANDER','department_id' => 29 ,  'cost' =>10.000]);
        City::create(['name' => 'TARAPACA' ,'department_id' => 29 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO INIRIDA' ,'department_id' => 30 ,  'cost' =>10.000]);
        City::create(['name' => 'BARRANCO MINAS' ,'department_id' => 30 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN FELIPE','department_id' => 30 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO COLOMBIA','department_id' => 30 ,  'cost' =>10.000]);
        City::create(['name' => 'LA GUADALUPE' ,'department_id' => 30 ,  'cost' =>10.000]);
        City::create(['name' => 'CACAHUAL' ,'department_id' => 30 ,  'cost' =>10.000]);
        City::create(['name' => 'PANA PANA' ,'department_id' => 30 ,  'cost' =>10.000]);
        City::create(['name' => 'MORICHAL','department_id' => 30 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JOSE DEL GUAVIARE','department_id' => 31 ,  'cost' =>10.000]);
        City::create(['name' => 'CALAMAR','department_id' => 31 ,  'cost' =>10.000]);
        City::create(['name' => 'EL RETORNO','department_id' => 31 ,  'cost' =>10.000]);
        City::create(['name' => 'MIRAFLORES','department_id' => 31 ,  'cost' =>10.000]);
        City::create(['name' => 'MITU','department_id' => 32 ,  'cost' =>10.000]);
        City::create(['name' => 'CARURU' ,'department_id' => 32 ,  'cost' =>10.000]);
        City::create(['name' => 'PACOA' ,'department_id' => 32 ,  'cost' =>10.000]);
        City::create(['name' => 'TARAIRA','department_id' => 32 ,  'cost' =>10.000]);
        City::create(['name' => 'PAPUNAUA ','department_id' => 32 ,  'cost' =>10.000]);
        City::create(['name' => 'YAVARATE' ,'department_id' => 32 ,  'cost' =>10.000]);
        City::create(['name' => 'PUERTO CARREÑO' ,'department_id' => 33 ,  'cost' =>10.000]);
        City::create(['name' => 'LA PRIMAVERA' ,'department_id' => 33 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA RITA','department_id' => 33 ,  'cost' =>10.000]);
        City::create(['name' => 'SANTA ROSALIA','department_id' => 33 ,  'cost' =>10.000]);
        City::create(['name' => 'SAN JOSE DE OCUNE' ,'department_id' => 33 ,  'cost' =>10.000]);
        City::create(['name' => 'CUMARIBO' ,'department_id' => 33 ,  'cost' =>10.000]);


    }
    }

